"""Add deck_id to game_room_players

Revision ID: 44cbe43b562f
Revises: 145128b0a162
Create Date: 2026-02-13 19:39:41.545762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cbe43b562f'
down_revision: Union[str, Sequence[str], None] = '145128b0a162'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deck_cards', type_='foreignkey')
    op.drop_constraint(None, 'decks', type_='foreignkey')
    op.add_column('game_room_players', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'game_room_players', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_room_players', type_='foreignkey')
    op.drop_column('game_room_players', 'deck_id')
    op.create_foreign_key(None, 'decks', 'cards', ['commander_scryfall_id'], ['scryfall_id'])
    op.create_foreign_key(None, 'deck_cards', 'cards', ['card_scryfall_id'], ['scryfall_id'])
    # ### end Alembic commands ###
